export const queryKey = {
  KAKAO_LOGIN: 'kakaoLogin',
  STORE_RANK: 'storeRank',
  STORE_INFO: 'storeInfo',
  STORE_DETAIL_DESIGN: 'storeDetailDesign',
  STORE_DETAIL_SIZE: 'storeDetailSize',
  STORE_DETAIL_INFO: 'storeDetailInfo',
  STORE_LINK: 'storeLink',
  STORE_COORDINATE_LIST: 'storeCoordinateList',
  STORE_STATIONS: 'storeStations',
  CAKE_RANK: 'cakeRank',
  USER: 'user',
  STATION_DESIGN_LIST: 'stationDesignList',
  STATION_STORE_LIST: 'stationStoreList',
  LIKED_STORE_DESIGN_LIST: 'likedStoreDesignList',
} as const;
