export const queryKey = {
  KAKAO_LOGIN: 'kakaoLogin',
  STORE_RANK: 'storeRank',
  STORE_INFO: 'storeInfo',
  STORE_DETAIL_DESIGN: 'storeDetailDesign',
  STORE_DETAIL_SIZE: 'storeDetailSize',
  STORE_DETAIL_INFO: 'storeDetailInfo',
  STORE_LINK: 'storeLink',
  STORE_COORDINATE_LIST: 'storeCoordinateList',
  SELECT_STORE_COORDINATE: 'selectStoreCoordinate',
  LIKES_STORE_COORDINATE_LIST: 'likesStoreCoordinateList',
  STORE_STATIONS: 'storeStations',
  CAKE_RANK: 'cakeRank',
  USER: 'user',
} as const;
