export const queryKey = {
  STORE_RANK: 'storeRank',
  DESIGN_LIST: 'designList',
  DESIGN_DETAIL: 'designDetail',
  KAKAO_LOGIN: 'kakaoLogin',
  LIKED_CAKE_LIST: 'likedCakeList',
  LIKED_STORE_LIST: 'likedStoreList',
  STORE_COORDINATE_LIST: 'storeCoordinateList',
  STORE_INFO: 'storeInfo',
  STORE_DETAIL_DESIGN: 'storeDetailDesign',
  STORE_DETAIL_SIZE: 'storeDetailSize',
  STORE_DETAIL_INFO: 'storeDetailInfo',
  STORE_LINK: 'storeLink',
  SELECT_STORE_COORDINATE: 'selectStoreCoordinate',
  LIKES_STORE_COORDINATE_LIST: 'likesStoreCoordinateList',
  STORE_STATIONS: 'storeStations',
  CAKE_RANK: 'cakeRank',
  CAKE_INFO: 'cakeInfo',
  USER: 'user',
  STATION_DESIGN_LIST: 'stationDesignList',
  STATION_STORE_LIST: 'stationStoreList',
  LIKED_STORE_DESIGN_LIST: 'likedStoreDesignList',
} as const;
