const storeData = {
  storeData: {
    storeId: 1,
    storeName: '버터뭉',
    address: '서울 중구 동호로 285-2 아이디어회관 301호',
    station: '홍대입구역',
    isLiked: true,
    imageUrl: '/example-img.png',
  },
  designData: [
    { cakeId: 1, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 2, imageUrl: '/example-img.png', isLiked: false },
    { cakeId: 3, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 4, imageUrl: '/example-img.png', isLiked: false },
    { cakeId: 5, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 6, imageUrl: '/example-img.png', isLiked: false },
    { cakeId: 7, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 8, imageUrl: '/example-img.png', isLiked: false },
    { cakeId: 9, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 10, imageUrl: '/example-img.png', isLiked: false },
    { cakeId: 11, imageUrl: '/example-img.png', isLiked: true },
    { cakeId: 12, imageUrl: '/example-img.png', isLiked: false },
  ],
  menuData: {
    sizes: [
      { sizeName: '도시락', price: 18000 },
      { sizeName: '미니', price: 18000 },
      { sizeName: '1호', price: 18000 },
      { sizeName: '2호', price: 18000 },
      { sizeName: '3호', price: 18000 },
    ],
    taste: '겉크림 - 크림치즈크림',
  },
  infoData: {
    monOpen: '09:00',
    monClose: '18:00',
    tueOpen: '09:00',
    tueClose: '18:00',
    wedOpen: '09:00',
    wedClose: '18:00',
    thuOpen: null,
    thuClose: null,
    friOpen: '09:00',
    friClose: '18:00',
    satOpen: '09:00',
    satClose: '18:00',
    sunOpen: '09:00',
    sunClose: '18:00',
    address: '서울특별시 중구 동호로 385-2 아이디어회관 301호',
    phone: '010-1234-1234',
  },
  kakaoLink: 'https://open.kakao.com/aeoirujaesl',
};

export default storeData;
